<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\User;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        // Ambil user pertama, atau buat user baru kalau belum ada
        $user = User::first() ?? User::factory()->create([
            'name' => 'Demo User',
            'email' => 'demo@example.com',
        ]);

        $books = [
            [
                'name' => 'The Silent Patient',
                'author' => 'Alex Michaelides',
                'publisher' => 'Celadon Books',
                'release_date' => '2019-02-05',
                'description' => 'A psychological thriller about a woman who refuses to speak after a shocking crime.',
                'isbn' => '9781250301697',
                'genre' => 'Mystery',
                'pages' => 336,
                'cover' => null,
            ],
            [
                'name' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'publisher' => 'T. Egerton',
                'release_date' => '1813-01-28',
                'description' => 'A timeless romance novel exploring love, family, and social expectations.',
                'isbn' => '9780141439518',
                'genre' => 'Romance',
                'pages' => 432,
                'cover' => null,
            ],
            [
                'name' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'publisher' => 'George Allen & Unwin',
                'release_date' => '1937-09-21',
                'description' => 'Bilbo Baggins embarks on an unforgettable fantasy adventure.',
                'isbn' => '9780261102217',
                'genre' => 'Fantasy',
                'pages' => 310,
                'cover' => null,
            ],
            [
                'name' => 'Dracula',
                'author' => 'Bram Stoker',
                'publisher' => 'Archibald Constable',
                'release_date' => '1897-05-26',
                'description' => 'A gothic horror novel introducing Count Dracula.',
                'isbn' => '9780141439846',
                'genre' => 'Horror',
                'pages' => 418,
                'cover' => null,
            ],
            [
                'name' => 'Dune',
                'author' => 'Frank Herbert',
                'publisher' => 'Chilton Books',
                'release_date' => '1965-08-01',
                'description' => 'An epic science fiction novel set on the desert planet Arrakis.',
                'isbn' => '9780441172719',
                'genre' => 'Science Fiction',
                'pages' => 688,
                'cover' => null,
            ],
            [
                'name' => 'The Da Vinci Code',
                'author' => 'Dan Brown',
                'publisher' => 'Doubleday',
                'release_date' => '2003-03-18',
                'description' => 'A fast-paced thriller involving secret societies and historical mysteries.',
                'isbn' => '9780307474278',
                'genre' => 'Thriller',
                'pages' => 489,
                'cover' => null,
            ],
            [
                'name' => 'Steve Jobs',
                'author' => 'Walter Isaacson',
                'publisher' => 'Simon & Schuster',
                'release_date' => '2011-10-24',
                'description' => 'The official biography of Apple co-founder Steve Jobs.',
                'isbn' => '9781451648539',
                'genre' => 'Biography',
                'pages' => 656,
                'cover' => null,
            ],
            [
                'name' => 'Sapiens',
                'author' => 'Yuval Noah Harari',
                'publisher' => 'Harper',
                'release_date' => '2015-02-10',
                'description' => 'A brief history of humankind from ancient times to the present.',
                'isbn' => '9780062316097',
                'genre' => 'History',
                'pages' => 498,
                'cover' => null,
            ],
            [
                'name' => 'Atomic Habits',
                'author' => 'James Clear',
                'publisher' => 'Avery',
                'release_date' => '2018-10-16',
                'description' => 'A practical guide to building good habits and breaking bad ones.',
                'isbn' => '9780735211292',
                'genre' => 'Self Help',
                'pages' => 320,
                'cover' => null,
            ],
            [
                'name' => 'The Psychology of Money',
                'author' => 'Morgan Housel',
                'publisher' => 'Harriman House',
                'release_date' => '2020-09-08',
                'description' => 'Lessons about wealth, greed, and happiness.',
                'isbn' => '9780857197689',
                'genre' => 'Finance',
                'pages' => 256,
                'cover' => null,
            ],
            [
                'name' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'publisher' => 'Prentice Hall',
                'release_date' => '2008-08-01',
                'description' => 'A handbook of agile software craftsmanship.',
                'isbn' => '9780132350884',
                'genre' => 'Programming',
                'pages' => 464,
                'cover' => null,
            ],
            [
                'name' => 'Design Patterns',
                'author' => 'Erich Gamma',
                'publisher' => 'Addison-Wesley',
                'release_date' => '1994-10-21',
                'description' => 'Classic software design patterns for object-oriented programming.',
                'isbn' => '9780201633610',
                'genre' => 'Software Engineering',
                'pages' => 395,
                'cover' => null,
            ],
            [
                'name' => 'Deep Learning',
                'author' => 'Ian Goodfellow',
                'publisher' => 'MIT Press',
                'release_date' => '2016-11-18',
                'description' => 'A comprehensive textbook on deep learning.',
                'isbn' => '9780262035613',
                'genre' => 'Artificial Intelligence',
                'pages' => 800,
                'cover' => null,
            ],
            [
                'name' => 'Introduction to Algorithms',
                'author' => 'Thomas H. Cormen',
                'publisher' => 'MIT Press',
                'release_date' => '2009-07-31',
                'description' => 'Comprehensive coverage of algorithms and data structures.',
                'isbn' => '9780262033848',
                'genre' => 'Computer Science',
                'pages' => 1312,
                'cover' => null,
            ],
            [
                'name' => 'The Lean Startup',
                'author' => 'Eric Ries',
                'publisher' => 'Crown Business',
                'release_date' => '2011-09-13',
                'description' => 'How today entrepreneurs use continuous innovation.',
                'isbn' => '9780307887894',
                'genre' => 'Business',
                'pages' => 336,
                'cover' => null,
            ],
            [
                'name' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'publisher' => 'Farrar, Straus and Giroux',
                'release_date' => '2011-10-25',
                'description' => 'Insights into human thinking and decision making.',
                'isbn' => '9780374533557',
                'genre' => 'Psychology',
                'pages' => 512,
                'cover' => null,
            ],
            [
                'name' => 'The Martian',
                'author' => 'Andy Weir',
                'publisher' => 'Crown',
                'release_date' => '2014-02-11',
                'description' => 'An astronaut struggles to survive alone on Mars.',
                'isbn' => '9780553418026',
                'genre' => 'Science Fiction',
                'pages' => 384,
                'cover' => null,
            ],
            [
                'name' => 'Gone Girl',
                'author' => 'Gillian Flynn',
                'publisher' => 'Crown Publishing',
                'release_date' => '2012-06-05',
                'description' => 'A psychological thriller about marriage and deception.',
                'isbn' => '9780307588371',
                'genre' => 'Crime',
                'pages' => 432,
                'cover' => null,
            ],
            [
                'name' => 'Norwegian Wood',
                'author' => 'Haruki Murakami',
                'publisher' => 'Kodansha',
                'release_date' => '1987-09-04',
                'description' => 'A coming-of-age novel exploring love and loss.',
                'isbn' => '9780375704024',
                'genre' => 'Drama',
                'pages' => 296,
                'cover' => null,
            ],
            [
                'name' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'publisher' => 'HarperOne',
                'release_date' => '1988-01-01',
                'description' => 'A philosophical novel about pursuing one\'s dreams.',
                'isbn' => '9780061122415',
                'genre' => 'Adventure',
                'pages' => 208,
                'cover' => null,
            ],
        ];

        foreach ($books as $book) {
            Book::create(array_merge($book, [
                'user_id' => $user->id,
            ]));
        }
    }
}
